/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.1 		*/
/*  Created On : 26-июл-2024 16:29:23 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE IF NOT EXISTS user_reg_info
(
    id bigint NOT NULL   DEFAULT NEXTVAL(('"user_reg_info_id_seq"'::text)::regclass),
    user_id uuid NOT NULL,
    reg_date varchar(24) NOT NULL,
    CONSTRAINT PK_user_reg_info PRIMARY KEY (id)
)
;

CREATE TABLE IF NOT EXISTS user_session_info
(
    id bigint NOT NULL   DEFAULT NEXTVAL(('"user_session_info_id_seq"'::text)::regclass),
    user_id uuid NOT NULL,
    last_logon varchar(24) NULL,
    CONSTRAINT PK_user_session_info PRIMARY KEY (id)
)
;

CREATE TABLE IF NOT EXISTS user_secret
(
    id bigint NOT NULL   DEFAULT NEXTVAL(('"user_secret_id_seq"'::text)::regclass),
    user_id uuid NOT NULL,
    is_active boolean NOT NULL,
    u_login varchar(20) NOT NULL,
    u_pass varchar(120) NOT NULL,
    CONSTRAINT PK_user_secret PRIMARY KEY (id)
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE IF NOT EXISTS user_reg_info_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE IF NOT EXISTS user_session_info_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE IF NOT EXISTS user_secret_id_seq INCREMENT 1 START 1
;
